### PR TITLE
WIP Add Plots sink support

### PR DESCRIPTION
**Pull request by davidanthoff**

### CODE REVIEW

**Comment by davidanthoff** [comment]
The problem here is the following. [This](https://github.com/JuliaPlots/Plots.jl/blob/master/src/series.jl#L163) line from Plots:
````julia
@recipe f{T<:Any}(::Type{T}, v::T) = v
````
and this line in this PR
````julia
@traitfn function RecipesBase.apply_recipe{X; IsIterableTable{X}}(d::Dict{Symbol,Any},::Type{X},source::X)
````
both add a method with the following signature:
````julia
function RecipesBase.apply_recipe{X}(d::Dict{Symbol,Any},::Type{X},source::X)
````
Essentially this PR overwrites the method from Plots.

Things still work because I also have
````julia
@traitfn function RecipesBase.apply_recipe{X; !IsIterableTable{X}}(d::Dict{Symbol,Any},::Type{X},source::X)
````
that gets called for anything that is not an ``IterableTable``, and it is functionally equivalent to the method generated by the original ``@recipe f{T<:Any}(::Type{T}, v::T) = v`` in Plots, but this is still not very elegant.

**Comment by mkborregaard** [comment]
Do you think this functionality was essentially added by https://github.com/JuliaPlots/StatPlots.jl/pull/82 or does this PR add some extra useful functionality?
I like your idea, though.

**Comment by davidanthoff** [comment]
I have to admit I don't really understand Plots.jl, so I'm not sure :) I think I'll close for now, and if folks want to see more integration than the StatsPlots.jl story, we can add it if someone has a concrete idea how to do it.

**Comment by mkborregaard** [comment]
I think the nice thing about the StatPlots method (barring that some people don't like a macro syntax) is that it's applied so early in the call handling process that it doesn't conflict with any other functionality.

**Pull request closed without merging**
