### PR TITLE
Add JuliaDB integration

### PR DESCRIPTION
**Pull request by davidanthoff**
Depends on JuliaComputing/JuliaDB.jl#45.

### CODE REVIEW

**Comment by davidanthoff** [comment]
FYI, @JeffBezanson and @Shashi

**Comment by shashi** [comment]
Can I use this integration to save a JuliaDB table to a CSV file?

**Comment by davidanthoff** [comment]
Yes, or a Feather file, I think that should work. Haven't tested it, though... I'm also not entirely sure how performant this will be, essentially if you do
````julia
save("filename.csv", jd)
````
where ``jd`` is a ``DTable``, it will call ``collect`` on it and then write the result out to a CSV file (or feather file, if you pick that).

**Comment by davidanthoff** [comment]
Ok, I just tried it, and it all works.

There is a naming conflict: both FileIO and JuliaDB export ``save`` and ``load``, so one has namespace qualify those calls when both packages are loaded.

**Pull request merged**
